Forum/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name="index"),
    path('<str:name>/', views.list,name="list"),
]

ForumSite/urls.py
from django.contrib import admin
from django.urls import path, include
from Forum import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('forums/',include(('Forum.urls','Forum'), namespace='Forum')),
    path('user/',include(('user.urls','user'), namespace='user')),
    path('forums/',include(('Topic.urls','Topic'), namespace='Topic')),
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Topic/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('<str:name>/<str:slug>', views.show,name="show"),
    path('<str:name>/<str:slug>/create_comment', views.create_comment,name="create_comment"),
    path('<str:forum>/post/create',views.create_post,name="create"),
    path('<str:slug>/post/lock',views.lock,name="lock"),
    path('<str:slug>/post/move',views.move,name="move"),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views
#from .views import RegisterView
app_name = "user"


urlpatterns = [
    path('login/',views.loginUser,name = "login"),
    path('register/',views.register,name = "register"),
    path('logout/',views.logoutUser,name = "logout"),
    path('panel/<str:username>',views.userPanel,name="userPanel"),
]

Forum/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.

def upload_to(instance,filename):
    return '%s/%s/%s'%('gayrimenkul',instance.slug,filename)

class Forum(models.Model):
	name = models.CharField(null=False,blank=False,verbose_name='Forum Name',unique=True, max_length=50)

	def __str__(self):
		return self.name

class SubForum(models.Model):
	name = models.CharField(null=False,blank=False,verbose_name='Sub Forum Name',unique=True, max_length=50)
	description = models.CharField(verbose_name='Forum Description', max_length=100, blank=True, null=True)
	icon = models.ImageField(verbose_name='Icon',upload_to=upload_to, null=True, blank=True)
	forum = models.ForeignKey(Forum, on_delete = models.CASCADE)
	comment_count = models.IntegerField(verbose_name = 'Comment Count', default=0, editable=False)
	topic_count = models.IntegerField(verbose_name = 'Topic Count', default=0, editable=False)

	def __str__(self):
		return self.name

class Moderator(models.Model):
	user = models.ForeignKey('user.User', on_delete = models.CASCADE)
	forum = models.ForeignKey(SubForum, on_delete = models.CASCADE)

	def __str__(self):
		return self.user.username

Topic/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify
import datetime
# Create your models here.

def min_length(value):
	if len(value) < 6:
		raise ValidationError(_("%(value)s can't be less than 6 characters."), params={'value':value})

class Topic(models.Model):
	owner = models.ForeignKey('user.User',blank=False,null=False,verbose_name='İçerik Sahibi Sahibi',on_delete=models.CASCADE)
	title = models.CharField(max_length=50,verbose_name='Başlık',help_text='Konu başlığı giriniz.',validators=[min_length])
	#min_length özelliği modelde yokmuş forms.CharField da varmış fakat ben bunu modelden direkt türeteceğim için kullanamyabilirim.
	#valid fonkunda bu min_length'i kendim kontrol etmeliyim. https://stackoverflow.com/questions/2470760/django-charfield-with-fixed-length-how
	#validator'a MinLengthValidator() ekledim, bu çözüm olabilir.
	content = RichTextField(verbose_name="İçerik",validators=[min_length])
	fixed = models.BooleanField(null=True,blank=True,editable=False,default='False')
	forum = models.ForeignKey('Forum.SubForum', blank=False, null=False, on_delete = models.CASCADE)
	slug = models.SlugField(max_length=122,default='',unique=True,null=False,verbose_name='Slug Alanı',editable=False)
	views = models.IntegerField(verbose_name = 'Views', default = 0, null = False, blank = False)
	created_date = models.DateTimeField(auto_now_add=True)
	updated_date = models.DateTimeField(auto_now=True)
	craeted_comment_date = models.DateTimeField(auto_now_add = True)
	lock_topic = models.BooleanField(default = False,verbose_name='Lock')
	
	def get_slug(self):
		return self.slug

	def __str__(self):
		return self.title

	def unique_slug(self,new_slug,orjinal_slug,index):
		if Topic.objects.filter(slug=new_slug):
			new_slug = '%s-%s'%(orjinal_slug,index)
			index += 1
			return self.unique_slug(new_slug=new_slug,orjinal_slug=orjinal_slug,index=index)
		return new_slug

	def save(self, *args, **kwargs):

		if self.slug == '':
			index=1
			new_slug = slugify(self.title)
			self.slug=self.unique_slug(new_slug=new_slug,orjinal_slug=new_slug,index=index)
			
		self.forum.topic_count += 1
		self.forum.save()

		super(Topic, self).save(*args,**kwargs)

		self.owner.topic_count += 1
		self.owner.save()

	def lock(self, *args, **kwargs):
		super(Topic,self).save(*args,**kwargs)

	def move(self, *args, **kwargs):
		self.forum.topic_count += 1
		pre_forum = args[0]
		pre_forum.topic_count -= 1
		pre_forum.save()
		self.forum.save()

		super(Topic,self).save()

	def views_plus(self, *args, **kwargs):
		self.views += 1
		super(Topic, self).save(*args,**kwargs)

	def update_comment_date(self, date, *args, **kwargs):
		self.craeted_comment_date = date
		super(Topic, self).save(*args, **kwargs)

	def delete(self, *args, **kwargs):
		self.forum.topic_count -= 1
		self.forum.save()

		super(Topic, self).delete(*args,**kwargs)

		self.owner.topic_count -= 1
		self.owner.save()

	class Meta:
		verbose_name = 'Topics'
		verbose_name_plural = 'Topics'
		ordering = ['-craeted_comment_date']

class Comment(models.Model):
	owner = models.ForeignKey('user.User', blank=False, null=False, on_delete=models.CASCADE)
	content = RichTextField(validators=[min_length], verbose_name='Comment')
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
	created_date = models.DateTimeField(auto_now_add=True)
	updated_date = models.DateTimeField(auto_now=True)

	def save(self, *args, **kwargs):
		self.topic.forum.comment_count += 1
		self.topic.forum.save()

		super(Comment, self).save(*args,**kwargs)

		self.owner.comment_count += 1
		self.owner.save()

		self.topic.update_comment_date(date = self.created_date)

	def delete(self, *args, **kwargs):
		self.topic.forum.comment_count -= 1
		self.topic.forum.save()

		super(Comment, self).delete(*args,**kwargs)

		self.owner.comment_count -= 1
		self.owner.save()

	class Meta:
		ordering = ['created_date']

Forum/forms.py
from django import forms
from .models import Forum, SubForum

class ForumForm(forms.ModelForm):

	class Meta:
		model = Forum
		fields = '__all__'

	def clean_name(self):
		name = self.cleaned_data['name']

		if name.isdigit():
			raise forms.ValidationError('The name cannot only consist of numbers.')

		if '@' in name:
			raise forms.ValidationError('The name cannot contain the @ character.')

		return name

class SubForumForm(forms.ModelForm):

	class Meta:
		model = SubForum
		fields = '__all__'

	def clean_name(self):
		name = self.cleaned_data['name']

		if name.isdigit():
			raise forms.ValidationError('The name cannot only consist of numbers.')

		if '@' in name:
			raise forms.ValidationError('The name cannot contain the @ character.')

		return name

	def clean_description(self):
		description = self.cleaned_data['description']

		if description.isdigit():
			raise forms.ValidationError('The description cannot only consist of numbers.')

		return description

user/forms.py
from django import forms
from .models import User, UserUpdateModel
from django.contrib.auth.forms import ReadOnlyPasswordHashField, UserChangeForm


class UserAdminCreationForm(forms.ModelForm):
	password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ('username', 'email', 'birthday')

	def clean_password2(self):
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')

		if password1 and password2 and password1 != password2:
			raise forms.ValidationError("Passwords don't match")
		return password2

	def save(self, commit=True):
		user = super(UserAdminCreationForm, self).save(commit=False)
		user.set_password(self.cleaned_data["password1"])
		if commit:
			user.save()
		return user

class UserAdminChangeForm(forms.ModelForm):
	password = ReadOnlyPasswordHashField()

	class Meta:
		model = User
		fields = {'email','avatar','birthday','admin','active','is_banned'}

	def clean_password(self):
		return self.initial['password']

class UserCreationForm(forms.ModelForm):
	password1 = forms.CharField(label = 'Password', widget=forms.PasswordInput)
	password2 = forms.CharField(label = 'Password Confirmation', widget= forms.PasswordInput)
	birthday = forms.DateField(label = 'Birthday', widget=forms.DateInput(attrs={'type':'date'}))

	class Meta:
		model = User
		fields = ['username']

	def clean_password2(self):
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError("Passwords don't match")
		return password2

	def save(self, commit=True):
		user = super(UserCreationForm, self).save(commit=False)
		user.set_password(self.clean_data['password1'])
		if commit:
			user.save()
		return user

class LoginForm(forms.Form):
	username = forms.CharField(label = 'Username')
	password = forms.CharField(widget=forms.PasswordInput)

class RegisterForm(forms.Form):
	class Meta:
		model = User
		fields = ['username', 'email','avatar', 'birthday', 'password', 'confirm']

	def __init__(self,*args,**kwargs):
		super(RegisterForm, self).__init__(*args,**kwargs)
		for field in self.fields:
			self.fields[field].widget.attrs = {'class':'form-control'}

	username = forms.CharField(label = 'Username')
	email = forms.EmailField()
	birthday = forms.DateField(label = 'Birthday', widget=forms.DateInput(attrs={'type':'date'}), required=False)
	password = forms.CharField(widget = forms.PasswordInput)
	confirm = forms.CharField(label = 'Confirm Password', widget = forms.PasswordInput)
	avatar = forms.ImageField(label = 'Avatar', required=False)

	def clean(self):
		username = self.cleaned_data.get('username')
		password = self.cleaned_data.get('password')
		confirm = self.cleaned_data.get('confirm')
		email = self.cleaned_data.get('email')
		avatar = self.cleaned_data.get('avatar')
		birthday = self.cleaned_data.get('birthday')
		
		if password and confirm and password != confirm:
			raise forms.ValidationError("Passwords doesn't match")
		if email == False:
			raise forms.ValidationError("A valid Email Address")

		values = {
		'username' : username,
		'password' : password,
		'email' : email,
		'avatar': avatar,
		'birthday' : birthday
		}

		return values

Forum/views.py
from django.shortcuts import render,redirect,Http404,get_object_or_404,HttpResponseRedirect,reverse
from .models import Forum, SubForum
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from Topic.models import Topic, Comment
from user.models import User
from Topic.forms import CommentForm, TopicForm
from user.forms import LoginForm

# Create your views here.

def index(request):
	total_topic = 0
	total_comment = 0

	forums = Forum.objects.all()
	subForums = SubForum.objects.all()

	for forum in subForums:
		total_topic += forum.topic_count
		total_comment += forum.comment_count

	last_ten_topic = Topic.objects.all().order_by('-id')[:10]
	last_ten_comment = Comment.objects.all().order_by('-id')[:10]
	last_ten_user = User.objects.all().order_by('-timestamp')[:10]
	most_posted_users = User.objects.all().order_by('-topic_count')[:10]
	total_user = User.objects.all().count()
	login_form = LoginForm()

	context = {
			'forums': forums,
			'subForums': subForums,
			'last_ten_user': last_ten_user,
			'last_ten_comment': last_ten_comment,
			'last_ten_topic': last_ten_topic,
			'login_form' : login_form,
			'most_posted_users' : most_posted_users,
			'total_topic' : total_topic,
			'total_comment' : total_comment,
			'total_user' : total_user,

		}

	return render(request,'forum.html', context)


def list(request,name):
	page = request.GET.get('page',1)
	subForum = SubForum.objects.get(name = name)
	topics = Topic.objects.filter(forum = subForum)
	paginator = Paginator(topics, 20)

	try:
		topics = paginator.page(page)
	except PageNotAnInteger:
		topics = paginator.page(1)
	except EmptyPage:
		topics = paginator.page(paginator.num_pages)

	return render(request,"topic_list.html",{'subForum':subForum, 'topics':topics})


	

templates/footer.html
<div class="container">
	

	<div class="subForum_header" style="padding: 5px;">
		<h5 align="center">Statistics</h5>
		Total Topic : {{total_topic}} <br>
		Total Comment : {{total_comment}} <br>
		Total User : {{total_user}} <br>
	</div>

</div>

templates/forum.html
{% extends 'base.html' %}
{% block body %}

<div class="container-fluid">
	<div class="row nav_header">

		<div class="col-3 nav_child" style="font-size:12px;">
			<h6 align="center" style="font-size: 12px;">Most Posted Users</h6>
			{% for user in most_posted_users %}
			<div class="row">
				<div class="col-10">
				<a align="left" href="#" style="font-weight: bold;color:{{ user.userpermission.get_color }}">
					{{ user }}
				</a>  
				</div>
				<div class="col-2">{{ user.topic_count }}</div>
			</div>
			{% endfor %}
		</div>

		<div class="col-3 nav_child">
			<h6 align="center" style="font-size: 12px;">Last Registered Users</h6>
			{% for user in last_ten_user %}
				<div class="forum_nav"><a href="#">{{user}}</a></div>
			{% endfor %}
		</div>

		<div class="col-3 nav_child">
			<h6 align="center" style="font-size: 12px;">Recent Comments</h6>
			{% for comment in last_ten_comment %}
				<div class="forum_nav"><a href="{% url 'Topic:show' comment.topic.forum comment.topic.slug %}">{{comment.topic}}</a></div>
			{% endfor %}
		</div>

		<div class="col-3 nav_child">
			<h6 align="center" style="font-size: 12px;">Recently Opened Topics</h6>
			{% for topic in last_ten_topic %}
				<div class="forum_nav"><a href="{% url 'Topic:show' topic.forum topic.slug %}">{{topic}}</a></div>
			{% endfor %}
		</div>

	</div>
	{% for forum in forums %}
		<div class="forum_header">
			{{forum}}
		</div>
		<div class="row subForum_header">
	    	<div class="col-9" align="center">Forum Name</div>
	    	<div class="col-1 border_lr">Topic Count</div>
	    	<div class="col-1">Comment Count</div>
	    	<div class="col-1 border_lr">Moderators</div>
		</div>
		{% for subForum in forum.subforum_set.union %}
		<div class="row subForum_header">
			<div class="col-9">
				{% if subforum.icon %}<img src="" class="subForum_icon"> {% endif %}
	    		<a href="{% url 'Forum:list' subForum.name %}" class="subForum_title">{{subForum.name}}</a> <br>
	    		<small class="description">{% if subForum.description %}{{subForum.description}}{% endif %}</small>
			</div>
			<div class="col-1 border_lr">{{subForum.topic_count}}</div>
			<div class="col-1">{{subForum.comment_count}}</div>
			<div class="col-1 border_lr">
				{% if subForum.moderator_set %}
				{% for mod in subForum.moderator_set.union %}
					<a href="#" style="font-size:10px;font-weight: bold;color:{{ mod.user.userpermission.get_color }};">{{mod}}</a><br>
				{% endfor %}
				{% endif %}
			</div>
		</div>
		{% endfor %}
	{% endfor %}
</div>

{% include "footer.html" %}
{% endblock %}

templates/navbar.html
{% load nav_helper %}
<div class="container" align="center">
	<div class="row" align="center">
		<div class="col-12">
			<a href="/"><img src="/media/forum_pngs/django.png" style="width:25%;"></a>
		</div>
		
	</div>

	<div class="col-4 subForum_header" style="padding: 5px;">
		{% if not request.user.is_authenticated %}
		<form method="POST" action="{% url 'user:login' %}">
			{% csrf_token %}
			<label style="width:75px;">Username</label> : <input type="text" name="username" id="id_username" required> <br>
			<label style="width:75px;">Password</label> : <input type="password" name="password" id="id_password" required> <br>
			<br>
			<button type="submit" class="btn-sm btn-primary">
		Sign in</button> OR <a href="{% url 'user:register' %}" class="btn-sm btn-success">Sign up</a>
		</form>
		{% else %}
		<i class="fas fa-user">Welcome</i>  <a href="{% url 'user:userPanel' request.user %}">
		{{request.user}}</a><br>
		<i class="fas fa-sign-out-alt"></i><a href="{% url 'user:logout' %}">Logout</a>
		{% endif %}
	</div>

	<div class="row">

		<div class="col-12 subForum_header" align="left">

			<div style="margin-left: 15px;"><i class="fas fa-map-signs" style="margin-right: 10px;"></i> {{ request.path|link_map|safe }}</div>
		</div>

	</div>
</div>

templates/show.html
{% extends 'base.html' %}
{% block body %}
{% load crispy_forms_tags %}
<div class="container">
	<div class="row forum_header">
		<div class="col-4">
			<i class="far fa-clock" style="margin-top:4px;"></i>  {{ topic.created_date }}
		</div>
		{% if request.user.is_staff %}
		<div class="dropdown col-3 offset-5">
		  <button class="btn btn-outline dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		    Dropdown button
		  </button>
		  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
		    <a class="dropdown-item" href="{% url 'Topic:lock' topic.slug %}">Lock Topic</a>
		    <a class="dropdown-item" href="{% url 'Topic:move' topic.slug %}">Move Topic</a>
		    
		  </div>
		</div>
		{% endif %}
	</div>
	<a style="margin-left:5px;" href="#comment_form" class="btn-sm btn-dark">Comment</a>
	<div class="row subForum_header">

		<div class="col-2 user_field" align="center">
			<a style="font-size: 16px;color:{{topic.owner.userpermission.get_color}}; {% if topic.owner.is_banned %}text-decoration: line-through;{% else %} text-decoration: none;{% endif %}font-weight: bold;margin-top:10px; width: 100%;background-color:white; padding:1px;" href="#">{{ topic.owner.username }}</a>
			<br>
			<img src="{{ topic.owner.userpermission.get_icon }}" style="width:100%;background-color:white;padding:1px;border-radius: 5px;">
			<br>
			<img src="{{ topic.owner.get_image_or_default }}" style="margin-top:5px;margin-bottom:5px;width: 100%;height: 80%;padding:1px;background-color:white;">
			<div style="font-size: 10px;background-color:white;border-radius: 5px;margin-bottom:3px;text-align: left;padding: 3px;">Registered Date: {{topic.owner.timestamp|date}}</div>
			<div style="background-color:white;border-radius: 5px;margin-bottom:3px;text-align: left;padding: 3px;">Comments: {{topic.owner.comment_set.count}}</div>
			<div style="background-color:white;border-radius: 5px;text-align: left;padding: 3px;margin-bottom:3px;">Topics: {{topic.owner.topic_set.count}}
			</div>
			<div style="font-size: 10px;background-color:white;border-radius: 5px;margin-bottom:3px;text-align: left;padding: 3px;">Last Login: {{topic.owner.last_login|date}}</div>
		</div>
		<div class="col-10">
		<strong><i class="far fa-newspaper"></i> Title : {{topic.title}}</strong>
		<hr>
		{{topic.content|safe}}
		</div>
	</div>
	{% for comment in comments %}
	<div class="row subForum_header">
		<div class="col-2 user_field" align="center">
			<a style="font-size: 16px;color:{{comment.owner.userpermission.get_color}}; text-decoration: none;font-weight: bold;margin-top:10px;margin-bottom:10px; width: 100%;background-color:white; padding:1px;" href="#">{{ comment.owner.username }}</a>
			<br>
			<img src="{{ comment.owner.userpermission.get_icon }}" style="width:100%;background-color:white;padding:1px;border-radius: 5px;">
			<br>
			<img src="{{ comment.owner.get_image_or_default }}" style="margin-top:5px;margin-bottom:5px;width: 100%;height: 80%;padding:1px;background-color:white; ">
			<div style="font-size: 10px;background-color:white;border-radius: 5px;margin-bottom:3px;text-align: left;padding: 3px;">Registered Date: {{comment.owner.timestamp|date}}</div>
			<div style="background-color:white;border-radius: 5px;margin-bottom:3px;text-align: left;padding: 3px;">Comments: {{comment.owner.comment_set.count}}</div>
			<div style="background-color:white;border-radius: 5px;text-align: left;padding: 3px;margin-bottom:3px;">Topics: {{comment.owner.topic_set.count}}</div>
			<div style="font-size: 10px;background-color:white;border-radius: 5px;margin-bottom:3px;text-align: left;padding: 3px;">Last Login: {{comment.owner.last_login|date}}</div>
		</div>
		<div class="col-10">
		<strong><i class="fas fa-comment"></i> {{comment.created_date}}</strong>
		<hr>
		{{comment.content|safe}}
		</div>
	</div>
	{% endfor %}
	
	{% if comments.has_other_pages %}
	<div class="subForum_header">
    <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
	{% if comments.has_previous %}
	    <li class="page-item"><a class="page-link" href="?page={{ comments.previous_page_number }}">&laquo;</a></li>
	{% else %}
	    <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
	{% endif %}
	{% for i in comments.paginator.page_range %}
	{% if comments.number == i %}
	    <li class="activate page-item"><span class="page-link">{{ i }}<span class="sr-only">(current)</span></span></li>
	{% else %}
	    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
	{% endif %}
	{% endfor %}
	{% if comments.has_next %}
	    <li class="page-item"><a class="page-link" href="?page={{ comments.next_page_number}}">&raquo;</a></li>
	{% else %}
	    <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
	{% endif %}
	</ul>
	</div>
	{% endif %}

	{% if topic.lock_topic %}
	{% if request.user.is_staff %}
	<div class="subForum_header" style="padding:10px;">
		<form method="POST" action="{% url 'Topic:create_comment' name topic.slug %}" class="form_style" align="center" id="comment_form">
			<div class="row">
				<div class="col-3"> </div>
				<div class="col-6" id="attention"></div>
				<div class="col-3"> </div>
			</div>
			{% csrf_token %}
			{{ comment_form.media }}
			{{ comment_form|crispy }}
			<button {% if not request.user.is_authenticated %} title="Logged in for comment" {% endif %} id="comment_button" type="submit" class="btn btn-outline-dark" onclick='auth(this)'>Comment</button>
		</form>
	</div>
	{% else %}
	<div class="subForum_header" style="padding:10px;" align="center">
		<i title="Locked Topic" class="fas fa-lock" style="font-size:64px;margin-top:5px;width: 100%;height: 100%;"></i>
	</div>
	{% endif %}
	{% else %}
	<div class="subForum_header" style="padding:10px;">
		<form method="POST" action="{% url 'Topic:create_comment' name topic.slug %}" class="form_style" align="center" id="comment_form">
			<div class="row">
				<div class="col-3"> </div>
				<div class="col-6" id="attention"></div>
				<div class="col-3"> </div>
			</div>
			{% csrf_token %}
			{{ comment_form.media }}
			{{ comment_form|crispy }}
			<button {% if not request.user.is_authenticated %} title="Logged in for comment" {% endif %} id="comment_button" type="submit" class="btn btn-outline-dark" onclick='auth(this)'>Comment</button>
		</form>
	</div>
	{% endif %}
</div>
<style>
	.user_field{
		border: 1px inset lightblue;
		background-color: lightblue;
		padding: 5px;
		width: 100%;
		height: 100%;
	}
	#attention{
		color:white;
		background: red;
		border: 1px;
		width: 60%;
	}
</style>

<script>
	function auth(){
		const is_authenticated = eval("{{ request.user.is_authenticated|lower }}")
		const attention_text = document.getElementById('attention')
		
		if(is_authenticated)
		{
			attention_text.innerText = ''
		}
		else
		{
			attention_text.innerText = 'You must logged in for apply comment!'
		}
	}

	window.onload = function(){button_clickable()}

	function button_clickable(){
		const button = document.getElementById('comment_button')
		const is_authenticated = eval("{{ request.user.is_authenticated|lower }}")

		if(!is_authenticated)
		{
			button.disabled = 'disabled'
		}
		auth()
	}
</script>
{% endblock %}

templates/topic_list.html
{% extends 'base.html' %}
{% load poll_extras %}
{% block body %}
<div class="container-fluid">
    <a href="{% url 'Topic:create' subForum.name %}" class="btn btn-primary" style="margin-left:6px;">New Post</a>
    <div class="forum_header">Forum Title : {{ subForum.name }}</div>
    <div>
        
        <div align="center" class="subForum_header">
            <div class="row">
                <div class="col-1"></div>
                <div class="col-7" style="text-align: left;">Title of Topic</div>
                <div class="col-2 border_lr">Last Comment</div>
                <div class="col-1">Comments</div>
                <div class="col-1 border_lr">Views</div>
            </div>
        </div>
        {% for topic in topics %}
        <div class="subForum_header" align="center">

            
            <div class="row">
                <div class="col-1" align="center">{% if topic.lock_topic %}<i title="Locked Topic" class="fas fa-lock" style="font-size:22px;margin-top:5px;width: 100%;"></i>{% else %}<i class="far fa-sticky-note" style="font-size:22px;margin-top:5px;"></i>{% endif %}</div>
                <div class="col-7" style="text-align: left;"><a href="{% url 'Topic:show' subForum.name topic.slug %}">{{topic.title}}</a><br> <small>{{topic.owner}}</small></div>
                <div class="col-2 border_lr" style="font-size: 11px;">
                    Tarih: {{ topic|last_index_date }}
                    <br> <strong>Gönderen: </strong>
                    {{ topic|last_index }}
                </div>
                <div class="col-1">{{ topic.comment_set.count }}</div>
                <div class="col-1 border_lr">{{ topic.views }}</div>
            </div>
            
        </div>
        {% endfor %}
        

    </div>
</div>


{% if topics.has_other_pages %}
    <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
{% if topics.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ topics.previous_page_number }}">&laquo;</a></li>
{% else %}
    <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
{% endif %}
{% for i in topics.paginator.page_range %}
{% if topics.number == i %}
    <li class="activate page-item"><span class="page-link">{{ i }}<span class="sr-only">(current)</span></span></li>
{% else %}
    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
{% endif %}
{% endfor %}
{% if topics.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ topics.next_page_number}}">&raquo;</a></li>
{% else %}
    <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
{% endif %}
</ul>
{% endif %}
<style>
    td:nth-child(even), th:nth-child(even) {
      background-color: #f2f2f2;
    }
</style>
{% endblock %}